name = input("Please enter your name: ")
age = input("Please enter your age: ")
course_code = input("Please enter your course code: ")
print(type(name))
print(type(age))
print(type(course_code))
print(f"Hello {name}, you are {age} years old and you are enrolled in the course {course_code}.")